sudo: false

language: java
jdk:
  - oraclejdk8

cache:
    directories:
        - $HOME/.m2
        - $HOME/apache-maven-3.3.9

before_cache:
    - rm -rf $HOME/.m2/repository/com/itdhq

before_script:
    - wget https://raw.githubusercontent.com/ITDSystems/alvex/master/scripts/mvn.sh -O ./mvnw
    - chmod +x mvnw
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then base64 -d <<< $MAVEN_DEPLOY_SETTINGS | tar -xz -C $HOME; fi'

install: true

script:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export FINAL_PHASE=deploy; else export FINAL_PHASE=package; fi'
    - ./mvnw clean $FINAL_PHASE

notifications:
  email:
    on_success: change
    on_failure: always
