sudo: false

language: java
jdk:
  - oraclejdk8

cache:
    directories:
        - $HOME/.m2
        - $HOME/apache-maven-3.3.9

before_cache:
    - rm -rf $HOME/.m2/repository/com/itdhq

before_script:
    - wget https://raw.githubusercontent.com/ITDSystems/alvex/master/scripts/mvn.sh -O ./mvnw
    - chmod +x mvnw
#    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then base64 -d <<< $MAVEN_DEPLOY_SETTINGS | tar -xz -C $HOME; fi'


script:
    - ./mvnw clean package

after_success:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./mvnw deploy; fi'

# notifications:
#   email:
#     recipients:
#       - alvex-build@itdhq.com
#     on_success: change
#     on_failure: always
